#! /bin/bash

#  ____  _   _
# |  _ \| \ | | Pradyun Narkadamilli
# | |_) |  \| | https://pradyungn.tech
# |  __/| |\  | MIT License
# |_|   |_| \_| Copyright 2020 Pradyun Narkadamilli

# My bspwm configuration on my personal machine

# autorandr --change

# nitrogen --restore

bspc config top_padding 0

bspc config border_width         3
bspc config window_gap          12

# Visual options
bspc config split_ratio         0.50
# bspc config borderless_monocle  true
# bspc config gapless_monocle     true

bspc config urgent_border_color "#ff5555"
bspc config focused_locked_border_color "#50fa7b"
bspc config normal_border_color "#37404c"
bspc config active_border_color "#37404c"
bspc config focused_border_color "#61afef"
bspc config presel_feedback_color "#4f6e87"


bspc rule -a Pavucontrol state=floating
bspc rule -a feh state=floating
bspc rule -a Discord desktop=^10 follow=on
bspc rule -a Telegram desktop=^10 follow=on
bspc rule -a Slack desktop=^10 follow=on
# bspc rule -a Matplotlib state=floating
# bspc rule -a Nitrogen state=tiled
# bspc rule -a floating_term state=floating center=true rectangle=640x480+0+0
# bspc rule -a Emacs state=floating center=true rectangle=640x800+0+0
bspc rule -a Emacs state=tiled
# bspc rule -a notion-nativefier-46aee8 state=floating center=true rectangle=1200x600+0+0
bspc rule -a Zathura state=tiled
bspc rule -a rofi border=on

bspc config focus_follows_pointer false
# wmname LG3D

# bspc subscribe node_state | while read -r _ _ _ node state status; do
    # if [[ "$state" == "floating" ]]; then
        # case "$status" in
            # on) xprop -id "$node" -remove _COMPTON_SHADOW;;
            # on) xprop -id "$node" -f _COMPTON_SHADOW 32c -set _COMPTON_SHADOW 1;;
        # esac
    # fi
# done &

# polybar -c ~/.config/polybar/config.ini main &

#if [ "$(bspc query -M | wc -l)" -eq "3" ]; then
#  bspc monitor $(bspc query -M | sed -n 1p) -d I II III IV
#  bspc monitor $(bspc query -M | sed -n 2p) -d V VI VII
#  bspc monitor $(bspc query -M | sed -n 3p) -d VIII IX X
#elif [ "$(bspc query -M | wc -l)" -eq "2" ]; then
#  bspc monitor $(bspc query -M | sed -n 1p) -d I II III IV V
#  bspc monitor $(bspc query -M | sed -n 2p) -d VI VII VIII IX X
#else
#  bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X
# fi

bspc monitor HDMI-0 -d I II III IV V
bspc monitor DVI-D-0 -d VI VII VIII IX X

sxhkd &
dunst &
redshift list &
picom -b

/home/ahuja/.screenlayout/default.sh
feh --bg-fill ~/Downloads/cal2.png

wmname LG3D

# MPD
#if ! pgrep -u $UID -x mpd >/dev/null; then
#    mpd &
#fi

# MPD MPRIS interface
#Jif ! pgrep -u $UID -x mpDris2 >/dev/null; then
#J    mpDris2 &
#fi

# compton
# if ! pgrep picom; then
#    picom -b
# fi

# exec --no-startup-id /home/ahuja/.screenlayout/default.sh

# Spawning Polybar on all connected monitors
polybar-msg cmd quit
# while pgrep polybar; do sleep 1; done
for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar -c ~/.config/polybar/config.ini main &
done
